name: bird_dl
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10.20
  - pip=22.3.1
  - matplotlib==3.5.3
  # pytorch
  - pytorch::pytorch=2.0.1
  - pytorch::torchaudio=2.0.2
  - pytorch::torchvision=0.15.2
